package it.demo.carsharing.repository;

import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.stereotype.Repository;

import it.demo.carsharing.model.Car;

@Repository
public interface CarRepository extends JpaRepository<Car, String> {
	//LE REPOSITORY SONO DELLE INTERFACCE CHE CONSENTONO L'INTEGRAZIONE DI METODI GIA PREDEFINITI DA SPRING,
	//PRINCIPALMENTE METODI CHE EFFETTUANO CRUD SUL DB COME FINDALL, GET BY ID, SAVE ETC.
	//L'INTERFACCIA PER FARE CIO ESTENDE LA JPAREPOSITORY, LA QUALE PER OGNI TIPO DI MODEL, OVVIAMENTE PASSANDOLE 
	//IL NOME DEL MODEL ED IL TIPO DELLA SUA CHIAVE, PREDISPONE DEI METODI CON I QUALI è POSSIBILE
	//EFFETTUARE TALI CRUD GIA PREDISPOSTE.
	//VOLENDO IN QUESTA INTERFACCIA SI POTREBBERO DEFINIRE NUOVI TIPI DI METODO, MA NON HO FATTO CIò IN NESSUNA REPO 
	//POICHè VOLEVO ATTENERMI ALLE CHIAMATE PRINCIPALI GIA PREDISPOSTE E FARE DEI WORK-AROUND AD ESSE COSI DA NON
	//CONFONDERE OLTREMODO LE COSE.

}
